"""Tests for grouping articles into deduplicated stories."""

from conftest import make_article

from lastweekintech import pipeline


def cluster(*articles):
    return pipeline.cluster_articles(list(articles))


class TestClusterArticles:
    def test_groups_the_same_event_reported_by_two_outlets(self):
        stories = cluster(
            make_article(
                title="Google announces new AI chip for data centers",
                url="https://a.example/1",
                source="Ars Technica",
            ),
            make_article(
                title="Google's new AI chip unveiled to boost data centers",
                url="https://b.example/1",
                source="WIRED",
            ),
        )
        assert len(stories) == 1
        assert {a.source for a in stories[0].articles} == {"Ars Technica", "WIRED"}

    def test_keeps_unrelated_stories_apart(self):
        stories = cluster(
            make_article(title="Apple releases a new iPhone", url="https://a.example/1"),
            make_article(title="Microsoft patches a Windows flaw", url="https://b.example/1"),
        )
        assert len(stories) == 2

    def test_does_not_merge_on_a_subset_of_words_alone(self):
        """token_set_ratio scores a strict subset at 100; that is not the same story."""
        stories = cluster(
            make_article(title="Apple", url="https://a.example/1"),
            make_article(
                title="Apple loses its long-running appeal over App Store commissions",
                url="https://b.example/1",
            ),
        )
        assert len(stories) == 2

    def test_does_not_merge_stories_that_only_share_common_words(self):
        stories = cluster(
            make_article(title="The best laptops for students", url="https://a.example/1"),
            make_article(title="The best headphones for travel", url="https://b.example/1"),
        )
        assert len(stories) == 2

    def test_clustering_does_not_depend_on_input_order(self):
        articles = [
            make_article(title="OpenAI launches GPT-6 for enterprise", url="https://a.example/1"),
            make_article(title="OpenAI launches GPT-6 for enterprises", url="https://b.example/1"),
            make_article(title="EU fines a chipmaker over antitrust", url="https://c.example/1"),
        ]
        forward = cluster(*articles)
        backward = cluster(*reversed(articles))
        assert sorted(len(s.articles) for s in forward) == sorted(len(s.articles) for s in backward)

    def test_titles_the_story_after_its_most_prominent_article(self):
        [story] = cluster(
            make_article(
                title="Blogger notes Google's new AI chip for data centers",
                url="https://a.example/1",
                hn_points=None,
            ),
            make_article(
                title="Google announces new AI chip for data centers",
                url="https://b.example/1",
                hn_points=450,
            ),
        )
        assert story.title == "Google announces new AI chip for data centers"

    def test_handles_an_empty_input(self):
        assert cluster() == []


class TestClusterArticlesOnRealHeadlines:
    """Cases taken verbatim from a measured live run of 508 articles.

    The old thresholds (token_set >= 80 and token_sort >= 60) produced 2
    multi-source clusters out of 499 stories, because outlets rewrite headlines
    hard enough to sink the ratios while still covering one event.
    """

    def test_groups_four_outlets_covering_one_event(self):
        stories = cluster(
            make_article(
                title="Anthropic to Add Invisible Watermarks to Claude-Generated Text",
                url="https://a.example/1",
                source="ExtremeTech",
            ),
            make_article(
                title="How Anthropic plans to watermark Claude's AI-generated text",
                url="https://b.example/1",
                source="BleepingComputer",
            ),
            make_article(
                title="Anthropic is watermarking text generated by Claude to comply with EU law",
                url="https://c.example/1",
                source="Engadget",
            ),
            make_article(
                title="Anthropic's 'Watermark' Text Adulteration in Claude Is a Perversion",
                url="https://d.example/1",
                source="Hacker News",
            ),
        )
        assert len(stories) == 1
        assert len({a.source for a in stories[0].articles}) == 4

    def test_groups_a_wire_story_rewritten_by_two_outlets(self):
        stories = cluster(
            make_article(
                title="France's top court blocks social media ban for under-15s",
                url="https://a.example/1",
                source="Hacker News",
            ),
            make_article(
                title="France's court just blocked Macron's plan to ban kids from social media",
                url="https://b.example/1",
                source="TechSpot",
            ),
        )
        assert len(stories) == 1

    def test_does_not_merge_two_products_from_one_brand(self):
        """A false merge the looser rule produced until the keyword floor rose."""
        stories = cluster(
            make_article(
                title="Samsung Galaxy Z Fold 8 Ultra review: The ultra foldable "
                "with an ultra price",
                url="https://a.example/1",
                source="Ars Technica",
            ),
            make_article(
                title="The Best Samsung Galaxy S26 Cases (2026): S26, S26+, and S26 Ultra",
                url="https://b.example/1",
                source="WIRED",
            ),
        )
        assert len(stories) == 2

    def test_does_not_merge_templated_headlines_that_share_only_a_date(self):
        """Six WIRED coupon posts merged into one "story" until numbers stopped counting."""
        stories = cluster(
            make_article(
                title="HelloFresh Promo Codes: 55% Off for August 2026", url="https://a/1"
            ),
            make_article(title="Columbia Promo Codes: 15% Off | August 2026", url="https://a/2"),
            make_article(title="Pura Promo Codes: $20 Off August 2026", url="https://a/3"),
        )
        assert len(stories) == 3

    def test_merges_near_verbatim_headlines_too_short_to_share_four_keywords(self):
        """A reposted headline is the same story however few significant words it has."""
        stories = cluster(
            make_article(title="Qwen3.8 27B", url="https://a.example/1", source="Hacker News"),
            make_article(title="Qwen3.8-27B", url="https://b.example/1", source="Techmeme"),
        )
        assert len(stories) == 1

    def test_does_not_merge_unrelated_stories_sharing_a_common_verb(self):
        stories = cluster(
            make_article(
                title="Give Google the boot by building your own search engine",
                url="https://a.example/1",
                source="The Register",
            ),
            make_article(
                title="Soup Raiders goes native: What you gain by building your own game engine",
                url="https://b.example/1",
                source="Hacker News",
            ),
        )
        assert len(stories) == 2

    def test_does_not_merge_two_unrelated_windows_security_stories(self):
        stories = cluster(
            make_article(
                title="Microsoft-vendetta hacker has a new zero day that gives system "
                "privileges on fully patched Windows",
                url="https://a.example/1",
                source="The Register",
            ),
            make_article(
                title="Microsoft Patches 398 Flaws Including a Windows Driver Zero-Day "
                "Under Active Attack",
                url="https://b.example/1",
                source="The Hacker News",
            ),
        )
        assert len(stories) == 2
